//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nombresito
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.historialcompra = new HashSet<historialcompra>();
            this.historialventa = new HashSet<historialventa>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> preciocompra { get; set; }
        public Nullable<int> precioventa { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual ICollection<historialcompra> historialcompra { get; set; }
        public virtual ICollection<historialventa> historialventa { get; set; }
    }
}
